### ISSUE TITLE
...

### ISSUE THREAD

**Issue by gennan** [bennytai/HongKongReflections#19]
...

**Comment by Gennan** [comment]
不過說實話這本書的內容還真的是挺好笑的 無聊的時候建議多看看

**Comment by Gennan** [comment]
我說話可能不是好聽 不過還是真的建議翻墻進國內看看微博和國內權威媒體的報道 再對比壹下外媒和香港媒體的報道 想想到底哪個說的更有道理吧 希望妳們不是和某些臺灣教授壹樣認為內陸還是吃方便面時候配不起榨菜 吃不起茶葉蛋的水平吧 對比下現在的香港 臺灣和現在的澳門 想想到底哪個才是妳們所想要的吧

**Comment by sinbadli** [comment]
写的是什么狗屁玩意，还副教授。这是有被迫害妄想症吧，得去医院看啊。按他的狗屁逻辑，地球现在没灭亡，你不能说地球未来不灭亡，这帮废青就赶紧跳海自绝好了，你还活个什么玩意。
